<<<<<<< HEAD
# Generated by Django 2.2.6 on 2019-10-24 06:07
=======
# Generated by Django 2.2.6 on 2019-10-22 10:07
>>>>>>> 9618242319c7f51fdbcf5a987557c23d2ffab8da

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
