# Generated by Django 2.2.6 on 2019-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191024_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegisterForm',
        ),
    ]
